### ISSUE TITLE
Center tagline

### ISSUE THREAD

**Issue by Commandcracker** [Kristify/Kristify#14]
Center tagline or resize the white background

![Screenshot_20221230_021942](https://user-images.githubusercontent.com/49335821/210025414-4d9c62b0-eeb0-4fb9-950a-a6d0abf6a1f5.png)

**Comment by 1Turtle** [comment]
It normally is supposed to scroll hen the text is longer than the white bar (for some reason it doesn't do that lately). But centering it if it fits inside it is a good point, I will look at that later.

**Comment by 1Turtle** [comment]
Solved with d3e6719991a46949c67a1b62934c46861886d3d4
Text should now be centered if it is not too long.
