### ISSUE TITLE
Kristify shuts down after sending a transaction to buy something

### ISSUE THREAD

**Issue by EmmaKnijn** [Kristify/Kristify#19]
See attached video for more information
https://user-images.githubusercontent.com/64010592/210521216-23c268e2-03ff-45e5-b88b-893be790569f.mp4

**Comment by EmmaKnijn** [comment]
The self variable was forgotten in the config, it might've been a good idea to not clear after kristify stops

**Comment by 1Turtle** [comment]
Because Kristify is open in another tab, it closes after the program is finished, hiding the error for the user.
If you see such errors, you can always try to run `"kristify>/src/init.lua`. We will make sure it wont close after a crash or something, thanks for the feedback!
